import type { Metadata } from "next";
import React from "react";
import './globals.css'; 
import { ThemeProvider } from "@/components/theme-provider"


export const metadata: Metadata = {
  title: "NovaLearn",
  description: "Generated by create next app",
};

export default function RootLayout({children,}: Readonly<{children: React.ReactNode;}>) {
  return (
    // suppressHydrationWarning is essential for next-themes to work without errors
    <html lang="en" suppressHydrationWarning>
      <body>
        <ThemeProvider
          attribute="class" // Tells next-themes to apply 'dark' class to <html>
          defaultTheme="system" // Use the user's OS preference by default
          enableSystem // Allow switching between system/light/dark
        >
          <main>
          {children}
        </main>
        </ThemeProvider>
      </body>
    </html>
  );
}